---
vcenter_hostname: "vcenter-01.infra.corp"
vcenter_cpi_user: "svc-k8s-vcenter"
vcenter_cpi_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  33616633343336346233303832306631333331393730643563306466643635323339643130306433
  3638656164643935656363353436323934333436333732330a343362636462643465383538323537
  31393234623532343266643734623161666339343566646263303536366363356562623265333937
  3730333134656130330a616137616335366336613633323933333466643563343335363363323034
  36396662613539646361656663313466316231646532626133666234396666306466
vcenter_datacenter: "Datacenter"
vcenter_thumbprint: 70:B8:80:D4:82:2B:D5:7B:3A:90:6A:1E:5F:D6:6A:DD:B8:5B:2B:22